name: Build-Debug

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - master

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
      - run: dotnet build ObservableCollection.WithoutSandbox.slnf -c Debug
      - run: dotnet test ObservableCollection.WithoutSandbox.slnf -c Debug --no-build
